meta_product_name: "TheHealthbook"

meta_title: "TheHealthbook - keep track of your medical history"

meta_description: "With TheHealthbook you keep always track of your medical history. Hold your health in your own hands with the sign up to TheHealthbook"

meta_image: "facebook_healthbook.jpg" # should exist in `app/assets/images/`
